package autonoma.simuladorcarro.views;

import autonoma.simuladorcarro.exceptions.AcelerarFrenarException;
import autonoma.simuladorcarro.exceptions.ApagadoAccidenteException;
import autonoma.simuladorcarro.exceptions.ApagarOtraVezException;
import autonoma.simuladorcarro.exceptions.CapacidadMotorException;
import autonoma.simuladorcarro.exceptions.EncenderOtraVezException;
import autonoma.simuladorcarro.exceptions.FrenaQuietoException;
import autonoma.simuladorcarro.exceptions.LimitePatinajeException;
import autonoma.simuladorcarro.exceptions.LlantaPatinajeException;
import autonoma.simuladorcarro.exceptions.MasSesentaKmxhException;
import autonoma.simuladorcarro.exceptions.RecuperaPatinajeException;
import javax.swing.JOptionPane;
import autonoma.simuladorcarro.models.Coche;
import autonoma.simuladorcarro.models.Simulador;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
/**
 *
 * @author Samuel Esteban Herrera Bedoya
 * @version 1.0.0
 * @since 2024-03-19
 */
public class VentanaPrincipal extends javax.swing.JFrame
{
    private Simulador simulador;
    private Clip clip;

    /**
     * Creates new form VentanaPrincipal
     * @param simulador
     */
    public VentanaPrincipal(Simulador simulador)
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.simulador = simulador;
    }

    private void reproducir(String ruta)
    {
        try
        {
            File archivoSonido = new File("C:\\Users\\User\\OneDrive\\Documentos\\NetBeansProjects\\SimuladorCarro\\src\\autonoma\\simuladorcarro\\sounds\\" + ruta);
            AudioInputStream a = AudioSystem.getAudioInputStream(archivoSonido);
            clip = AudioSystem.getClip();
            clip.open(a);
            clip.start();
        } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
            System.out.println("Error al reproducir sonido del archivo " + ruta);
        }
    }
    
    private void mostrarVariablesCoche() 
    {
        Coche coche = simulador.getCoche();
        boolean motorPrendido = coche.getTipoMotor().isPrendido();
        String texto = "Estado del motor: " + (motorPrendido ? "Encendido" : "Apagado");
        texto = texto + "Velocidad: " + (coche.getVelocidad());
        texto = texto + "Patinando: " + (coche.isPatinando() ? "SI" : "NO");
        MuestraVariables.setText(texto);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelCarro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Encender = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Apagar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Acelerar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Frenar = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        FrenoMano = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        MuestraVariables = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simuladorcarro/images/porDentro.jpeg"))); // NOI18N

        javax.swing.GroupLayout PanelCarroLayout = new javax.swing.GroupLayout(PanelCarro);
        PanelCarro.setLayout(PanelCarroLayout);
        PanelCarroLayout.setHorizontalGroup(
            PanelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCarroLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelCarroLayout.setVerticalGroup(
            PanelCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Encender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EncenderMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simuladorcarro/images/encender.png"))); // NOI18N

        javax.swing.GroupLayout EncenderLayout = new javax.swing.GroupLayout(Encender);
        Encender.setLayout(EncenderLayout);
        EncenderLayout.setHorizontalGroup(
            EncenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EncenderLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        EncenderLayout.setVerticalGroup(
            EncenderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Apagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApagarMouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simuladorcarro/images/apagar.png"))); // NOI18N

        javax.swing.GroupLayout ApagarLayout = new javax.swing.GroupLayout(Apagar);
        Apagar.setLayout(ApagarLayout);
        ApagarLayout.setHorizontalGroup(
            ApagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ApagarLayout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(37, 37, 37))
        );
        ApagarLayout.setVerticalGroup(
            ApagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Acelerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AcelerarMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simuladorcarro/images/acelerar.jpg"))); // NOI18N

        javax.swing.GroupLayout AcelerarLayout = new javax.swing.GroupLayout(Acelerar);
        Acelerar.setLayout(AcelerarLayout);
        AcelerarLayout.setHorizontalGroup(
            AcelerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AcelerarLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(51, 51, 51))
        );
        AcelerarLayout.setVerticalGroup(
            AcelerarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Frenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FrenarMouseClicked(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simuladorcarro/images/frenar.jpg"))); // NOI18N

        javax.swing.GroupLayout FrenarLayout = new javax.swing.GroupLayout(Frenar);
        Frenar.setLayout(FrenarLayout);
        FrenarLayout.setHorizontalGroup(
            FrenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrenarLayout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(51, 51, 51))
        );
        FrenarLayout.setVerticalGroup(
            FrenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autonoma/simuladorcarro/images/palanca.jpg"))); // NOI18N

        javax.swing.GroupLayout FrenoManoLayout = new javax.swing.GroupLayout(FrenoMano);
        FrenoMano.setLayout(FrenoManoLayout);
        FrenoManoLayout.setHorizontalGroup(
            FrenoManoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        FrenoManoLayout.setVerticalGroup(
            FrenoManoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrenoManoLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MuestraVariables.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Encender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Apagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Acelerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Frenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FrenoMano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MuestraVariables, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Encender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Acelerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Frenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FrenoMano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(MuestraVariables, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EncenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EncenderMouseClicked
        try
        {
            System.out.println("entre");
            simulador.prenderCoche();
            reproducir("encender.wav");
        } catch (EncenderOtraVezException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } finally {
            mostrarVariablesCoche();
        }
    }//GEN-LAST:event_EncenderMouseClicked

    private void ApagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApagarMouseClicked
        try 
        {
            simulador.apagarCoche(this.simulador.getCoche());
            reproducir("apagar.wav");
        } catch (ApagarOtraVezException | MasSesentaKmxhException | ApagadoAccidenteException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        } finally {
            mostrarVariablesCoche();
        }        
    }//GEN-LAST:event_ApagarMouseClicked

    private void AcelerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AcelerarMouseClicked
        try 
        {
            if(!this.simulador.getCoche().isPatinando())
            {
                Integer aceleracion = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingreses velocidad que desea acelerar"));
                simulador.acelerarCoche(aceleracion);
                reproducir("acelerar.wav");
            }else{
                JOptionPane.showMessageDialog(this, "El carro esta patinando, no puede acelerar");
                stopPatinajeCarro();
            }
            
        } catch (AcelerarFrenarException | RecuperaPatinajeException | ApagadoAccidenteException | ApagarOtraVezException | CapacidadMotorException | InterruptedException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } finally {
            mostrarVariablesCoche();
        }
    }//GEN-LAST:event_AcelerarMouseClicked

    public void stopPatinajeCarro() throws InterruptedException
    {
        this.simulador.getCoche().LlantaStopPatina();
        JOptionPane.showMessageDialog(this, "El carro dejo de patinar, frene si es necesario");
    }
    
    private void FrenarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FrenarMouseClicked
        try 
        {
            if(!this.simulador.getCoche().isPatinando())
            {
                Integer intensidadFrenado = Integer.parseInt(JOptionPane.showInputDialog(this, "Ingreses la intensidad de frenado"));
                simulador.frenarCoche(intensidadFrenado);
                reproducir("acelerar.wav");
            }else{
                JOptionPane.showMessageDialog(this, "El carro esta patinando, no puede frenar");
            }
        } catch (LlantaPatinajeException | AcelerarFrenarException | LimitePatinajeException | FrenaQuietoException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        } finally {
            mostrarVariablesCoche();
        }
    }//GEN-LAST:event_FrenarMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acelerar;
    private javax.swing.JPanel Apagar;
    private javax.swing.JPanel Encender;
    private javax.swing.JPanel Frenar;
    private javax.swing.JPanel FrenoMano;
    private javax.swing.JLabel MuestraVariables;
    private javax.swing.JPanel PanelCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}

